DROP TABLE IF EXISTS TBL_BEACHES;
 
CREATE TABLE TBL_BEACHES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  latitude VARCHAR(250) NOT NULL,
  longitude VARCHAR(250) NOT NULL
);